---
name: Packer Validate on Pull Requests

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the main branch
on:
  # Workflow is triggered on pull requests
  pull_request:
    # Workflow will only be triggered for pull requests on "master" branch
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
        
  build: 
    runs-on: ubuntu-latest
    steps:
  
    # Ref: https://github.com/marketplace/actions/packer-github-actions
    - name: build Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -syntax-only # only validate syntax
        target: ami.json

